/** @file     Rte_WdgM_Test.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.2  (R4.0 backend version: v7.8.5 (Build 46241))
  */

#include "Rte_WdgM_Test.h"

uint8 TestWdgM_TestNumber=0;	/* test number */

static boolean lTestWdgM_StopPetWdg=FALSE;
static boolean lTestWdgM_Started_Status=FALSE;
static uint32 TestWdgM_Counter=0;


/* --------------------------------------------------------------------------- */
/* RTE Event: /WdgM_Test/WdgM_Test/WdgM_Test_IB/TimingEvent */


FUNC(void, WdgM_Test_CODE) WdgM_Test_func(void)
{
#ifdef OLD_WATCHDOG
	static uint8 last_TestNumber=0;
	uint8 lTestNewNumber;

	if(lTestWdgM_StopPetWdg==FALSE)	/* if lTestWdgM_StopPetWdg=TRUE, stop petting watchdog */
		//Rte_Call_RPort_Alive_CheckpointReached(0);	/* Report to WdgM Alive supervision for CheckpointId 0 */

	lTestNewNumber=Rte_IRead_RE_WdgM_Test_RPort_TestRequested_uint8();

	/* increment counter */
	TestWdgM_Counter++;

	/* trigger on change */
	if(last_TestNumber!=lTestNewNumber)
	{
		last_TestNumber=lTestNewNumber;
		if((lTestNewNumber>0)&&(lTestNewNumber<=2))
		{
			TestWdgM_TestNumber=last_TestNumber;
		}
	}

	if((lTestWdgM_Started_Status==FALSE)&&(TestWdgM_TestNumber!=0))		/* no test started */
	{
		TestWdgM_Counter=0;		/* reset test counter */
		lTestWdgM_Started_Status=TRUE;	/* start testing */
	}
	else	/* lTestWdgM_Started_Status==FALSE */
	{
		if(TestWdgM_TestNumber==1)
		{
			if((TestWdgM_Counter>=10)&&(TestWdgM_Counter<20))	/* after 1s and for 1s */
			{
				lTestWdgM_StopPetWdg=TRUE;	/* flag to start creating default */
			}
			else if (TestWdgM_Counter>=20)
			{
				lTestWdgM_StopPetWdg=FALSE;	/* stop creating default */
				lTestWdgM_Started_Status=FALSE;	/* test is done */
				TestWdgM_TestNumber=0;
			}
		}
		else if(TestWdgM_TestNumber==2)
		{
			if(TestWdgM_Counter>=10)	/* after 1s */
			{
				lTestWdgM_StopPetWdg=TRUE;	/* start creating default */
				/* no test end, watchdog should reset the board */
			}
		}
	}

	/* Report to WdgM Alive supervision for CheckpointId 1 */
	//Rte_Call_RPort_Alive_CheckpointReached(1);
#endif
}

