/** @file     Rte_WdgM_BswSupervisedEntity.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.2  (R4.0 backend version: v7.8.5 (Build 46241))
  */

#include "Rte_WdgM_BswSupervisedEntity.h"

/* for LED blinking */
#include "Dio.h"
#define BLINK_PERIOD_TICKS	50
#define BLINK_PERIOD_FAILED_TICKS	10

/* --------------------------------------------------------------------------- */
/* RTE Event: /WdgM_BswSupervisedEntity/WdgM_BswSupervisedEntity/BswSupervisedEntity_SwcInternalBehavior/TimingEvent_0 */

FUNC(void, WdgM_BswSupervisedEntity_CODE) BswSE_RunnableEntity_func(void)
{
#ifdef OLD_WATCHDOG
	static uint32 BswSE_Counter=0;
	static uint32 BswSE_BlinkPeriod=BLINK_PERIOD_TICKS;
	/* Inform WdgM that BSW checkpoint is reached */
	Rte_Call_RPort_Alive_CheckpointReached(0);

	if(RTE_MODE_WdgMMode_SUPERVISION_FAILED==Rte_Mode_RPort_GlobalMode_currentMode())
		BswSE_BlinkPeriod=BLINK_PERIOD_FAILED_TICKS;
	else if(RTE_MODE_WdgMMode_SUPERVISION_OK==Rte_Mode_RPort_GlobalMode_currentMode())
		BswSE_BlinkPeriod=BLINK_PERIOD_TICKS;

	/* Blink LED On/Off. Period=500ms or 100ms */
	BswSE_Counter++;
	// if(BswSE_Counter>BswSE_BlinkPeriod/2)
		// Dio_WriteChannel(DioConf_DioChannel_TRB_LED, 0);
	// else
		// Dio_WriteChannel(DioConf_DioChannel_TRB_LED, 1);
	if(BswSE_Counter>=BswSE_BlinkPeriod)
		BswSE_Counter=0;

	/* Inform WdgM that BSW checkpoint is reached */
	Rte_Call_RPort_Alive_CheckpointReached(1);
#endif
}

