
/******************************************************************************
* Gotion, Inc. CONFIDENTIAL                                                   *
* Copyright (c) 2017 Gotion, Inc, All Rights Reserved.                        *
*                                                                             *
* This document contains proprietary information belonging to Gotion Inc.     *
* Transmittal, reproduction, dissemination and/or editing of this document    *
* as well as utilization of its contents and communication there of to        *
* others without express authorization are prohibited. Offenders will         *
* be held liable for payment of damages. All rights created by patent         *
* grant or registration of a utility model or design patent are reserved.     *
*******************************************************************************
* @file   Software_Version.h                                                  *
*                                                                             *
* @Version 1.0                                                                *
*                                                                             *
* @Generated On: 3/10/2021 11:30:09 AM                                       *
*                                                                             *
* @brief  Autogenerated header containing software version ID's               *
*                                                                             *
* Changeable by user:  NO                                                     *
*                                                                             *
******************************************************************************/

#ifndef _SOFTWARE_VERSION_H_
#define _SOFTWARE_VERSION_H_

/******************************* Includes ************************************/
#include "Platform_Types.h"
/************************** Global Macro Definitions *************************/
#define BE14_CONST_VALUE		"CAKL0103E09"
#define F195_CONST_VALUE		"03.02.25"

/*************************** Global Typedefs ********************************/

/********************** Global Constant Declarations ************************/

/*********************** Global Variable Declarations *************************/

/*********************** Global Function Declarations *************************/

#endif /* _SOFTWARE_VERSION_H_ */

