/*=====================DO NOT EDIT - AUTO-GENERATED CODE=====================*/
/******************************************************************************
* Gotion, Inc. CONFIDENTIAL                                                   *
* Copyright (c) 2017 Gotion, Inc, All Rights Reserved.                        *
*                                                                             *
* This document contains proprietary information belonging to Gotion Inc.     *
* Transmittal, reproduction, dissemination and/or editing of this document    *
* as well as utilization of its contents and communication there of to        *
* others without express authorization are prohibited. Offenders will         *
* be held liable for payment of damages. All rights created by patent         *
* grant or registration of a utility model or design patent are reserved.     *
*******************************************************************************
* @file   Software_Name.c                                                     *
*                                                                             *
* @Version 1.0                                                                *
*                                                                             *
* @Generated On: 3/10/2021 11:30:09 AM											      *
*                                                                             *
* @brief  Autogenerated file that contains a variable whose name is the		  *
		  software version - this is used by the A2L gen tool to distinguish  *
		  the working set													  *
*                                                                             *
* Changeable by user:  NO                                                     *
*                                                                             *
******************************************************************************/

/**************************** Prebuild checks ********************************/

/******************************* Includes ************************************/
#include "Platform_Types.h"
#include "Software_Version.h"
/************************* Private Macro Definitions ************************/

/*************************** Private Typedefs ********************************/

/*********************** Private Function Prototypes *************************/

/*********************** Global Constant Definitions *************************/

/*********************** Global Variable Definitions *************************/
#pragma section ".software_version_internal" 
const char CAKL0103E09 [] __attribute__((aligned(16))) = "CAKL0103E09";
#pragma section

#pragma section ".software_version_customer" 
const char Ce_CustomerSoftwareVersion [] __attribute__((aligned(16))) = "03_02_25";
#pragma section
/*********************** Private Constant Definitions ************************/

/*********************** Private Variable Definitions ************************/

/*********************** Global Function Definitions *************************/

/*********************** Private Function Definitions ************************/


